In [1]:
import pm4py
import sys
import random

import pandas as pd
sys.path.append("../../TaskExecutionTimeMining")

from event_log_transformer import *
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 200)

In [2]:
file_path = '../../../data/BPI Challenge 2017.xes'
event_log = pm4py.read_xes(file_path)
event_log

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
parsing log, completed traces :: 100%|██████████| 31509/31509 [00:28<00:00, 1103.53it/s]

,Action,org:resource,concept:name,EventOrigin,EventID,lifecycle:transition,time:timestamp,case:LoanGoal,case:ApplicationType,case:concept:name,case:RequestedAmount,FirstWithdrawalAmount,NumberOfTerms,Accepted,MonthlyCost,Selected,CreditScore,OfferedAmount,OfferID
0,Created,User_1,A_Create Application,Application,Application_652823628,complete,2016-01-01 09:51:15.304000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,statechange,User_1,A_Submitted,Application,ApplState_1582051990,complete,2016-01-01 09:51:15.352000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Created,User_1,W_Handle leads,Workflow,Workitem_1298499574,schedule,2016-01-01 09:51:15.774000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Deleted,User_1,W_Handle leads,Workflow,Workitem_1673366067,withdraw,2016-01-01 09:52:36.392000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Created,User_1,W_Complete application,Workflow,Workitem_1493664571,schedule,2016-01-01 09:52:36.403000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1202262,Deleted,User_1,W_Call after offers,Workflow,Workitem_1817549786,ate_abort,2017-01-06 06:33:02.212000+00:00,Home improvement,New credit,Application_1350494635,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1202263,Created,User_1,W_Call after offers,Workflow,Workitem_363876066,schedule,2017-01-06 06:33:02.221000+00:00,Home improvement,New credit,Application_1350494635,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1202264,statechange,User_28,A_Cancelled,Application,ApplState_1869071797,complete,2017-01-16 09:51:21.114000+00:00,Home improvement,New credit,Application_1350494635,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1202265,statechange,User_28,O_Cancelled,Offer,OfferState_420066181,complete,2017-01-16 09:51:21.139000+00:00,Home improvement,New credit,Application_1350494635,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Offer_1580299144
1202266,Deleted,User_28,W_Call after offers,Workflow,Workitem_1934044935,withdraw,2017-01-16 09:51:21.146000+00:00,Home improvement,New credit,Application_1350494635,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
start_end_event_log2 = TransformEventLog.start_end_event_log_all(event_log)
start_end_event_log2 = TransformEventLog.seconds_in_day(start_end_event_log2, 'time:timestamp_start')
start_end_event_log2 = TransformEventLog.day_of_week(start_end_event_log2, 'time:timestamp_start')

transformer = TransformEventLog()
start_end_event_log2 = transformer.index_based_encode(
    start_end_event_log2,
    ['org:resource_start', 'concept:name'],
    max_prefix_len=3
)

start_end_event_log2

,case:concept:name,time:timestamp_start,time:timestamp_complete,duration_seconds,org:resource_start_1,concept:name_1,org:resource_start_2,concept:name_2,org:resource_start_3,concept:name_3
0,Application_1000086665,2016-08-03 15:57:21.963000+00:00,2016-08-03 15:58:28.286000+00:00,66.323,User_1,W_Handle leads,None,None,None,None
1,Application_1000086665,2016-08-03 15:58:28.293000+00:00,2016-08-04 13:39:29.557000+00:00,78061.264,User_1,W_Handle leads,User_1,W_Complete application,None,None
2,Application_1000086665,2016-08-04 13:39:29.557000+00:00,2016-08-04 13:50:12.281000+00:00,642.724,User_1,W_Handle leads,User_1,W_Complete application,User_14,W_Complete application
3,Application_1000158214,2016-06-02 10:14:27.227000+00:00,2016-06-02 10:15:36.752000+00:00,69.525,User_1,W_Handle leads,None,None,None,None
4,Application_1000158214,2016-06-02 10:15:36.764000+00:00,2016-06-06 08:02:16.549000+00:00,337599.785,User_1,W_Handle leads,User_1,W_Complete application,None,None
...,...,...,...,...,...,...,...,...,...,...
94496,Application_999993467,2016-07-05 16:21:02.384000+00:00,2016-07-05 16:21:17.995000+00:00,15.611,User_23,W_Complete application,User_23,W_Complete application,None,None
94497,Application_999993467,2016-07-05 16:21:17.995000+00:00,2016-07-07 13:06:03.240000+00:00,161085.245,User_23,W_Complete application,User_23,W_Complete application,User_23,W_Complete application
94498,Application_999993812,2016-10-06 13:57:05.066000+00:00,2016-10-06 13:58:22.449000+00:00,77.383,User_1,W_Handle leads,None,None,None,None
94499,Application_999993812,2016-10-06 13:58:22.454000+00:00,2016-10-07 09:38:21.802000+00:00,70799.348,User_1,W_Handle leads,User_1,W_Complete application,None,None
94500,Application_999993812,2016-10-07 09:38:21.802000+00:00,2016-10-07 09:45:49.544000+00:00,447.742,User_1,W_Handle leads,User_1,W_Complete application,User_104,W_Complete application

In [6]:
# Identify columns where all values are NaN
all_nan_cols = start_end_event_log2.columns[start_end_event_log2.isna().all()]
print("Columns with only NaN values:")
print(all_nan_cols.tolist())

start_end_event_log2 = start_end_event_log2.drop(columns=all_nan_cols)

Columns with only NaN values:
[]

In [7]:
random.seed(42)

train, test = pm4py.ml.split_train_test(start_end_event_log2, case_id_key='case:concept:name')

In [12]:
print(train.shape, test.shape)
print(train['case:concept:name'].unique().shape, test['case:concept:name'].unique().shape)

(496466, 182) (123317, 182)
(24541,) (6068,)

In [8]:
train.to_csv('../../../data/BPIC2017/transformed_event_logs_indexbased/BPIC2017_train.csv', index=False, date_format='%Y-%m-%d %H:%M:%S.%f')
train.to_pickle('../../../data/BPIC2017/transformed_event_logs_indexbased/BPIC2017_train.pickle')

In [9]:
test.to_csv('../../../data/BPIC2017/transformed_event_logs_indexbased/BPIC2017_test.csv', index=False, date_format='%Y-%m-%d %H:%M:%S.%f')
test.to_pickle('../../../data/BPIC2017/transformed_event_logs_indexbased/BPIC2017_test.pickle')